[package]
name = "rust_chess_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
indoc = "2.0.3"
strum = "0.26.1"
strum_macros = "0.26.1"
