name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Run slow tests
      run: cargo test --release --verbose -- --ignored
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run benchmark tests
      run: cargo bench --verbose
