name: Rust

on: [push, fork]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update nightly && rustup default nightly
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update nightly && rustup default nightly
    - name: Run tests
      run: cargo test --release --verbose
    - name: Run slow tests
      run: cargo test --release --verbose -- --ignored
  bench-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update nightly && rustup default nightly
    - name: Run benchmark tests
      run: cargo bench --verbose
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Rust
      run: rustup update nightly && rustup default nightly
    - name: Run benchmark tests
      run: make && ./rce --bench
